Project: Private events
OlukaDenis/private-events pull request #5
Opened 2020-02-18 01:30 UTC by OlukaDenis

Complete all the implementations
- Authentication
- Associations

2020-02-18 02:11 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following changes need to be done before moving on ⬇️** 

#### Tests

* [x] models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2020-02-18 16:41 UTC, OlukaDenis commented
Added the Tests

2020-02-18 19:24 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @OlukaDenis 

Thank for the improvements but it's not sufficient. Take a lot on these screenshots
![Screenshot_2020-02-18_20-18-35](https://user-images.githubusercontent.com/8848104/74770330-51d47a80-528c-11ea-9f34-92a2ff55201c.png)
![Screenshot_2020-02-18_20-18-59](https://user-images.githubusercontent.com/8848104/74770335-539e3e00-528c-11ea-9e22-1e269b3fd911.png)

Also, you didn't write any integration tests. Please, read [that article](https://thoughtbot.com/blog/rspec-integration-tests-with-capybara) to learn more about writing integrations tests.

Kindly make the changes and submit a new code review request.
Thanks

Mael FOSSO

2020-02-18 19:48 UTC, OlukaDenis commented
Thanks for the article but the tests run smoothly form my end.

2020-02-19 14:39 UTC, mcrd25 requested changes
# Changes Required 🔍 👀 

Hi Denis! 👋 

Good job with the tests! There are only two minor things left to get the 👍 

#### Required Changes
- Remove all commented out code as can be seen from review comments
- When I click on "Happening" (the nav header) I get following error:
![Screen Shot 2020-02-19 at 10 02 09 AM](https://user-images.githubusercontent.com/31193823/74844371-bf6fbd80-5303-11ea-9298-ef1279f78295.png)

#### Additional Suggestions [OPTIONAL]
- [OPTIONAL] Consider adding a link to profile in nav: Can only access profile by going to route directly besides when I initially log in.


We are almost there! Had it not been for that one bug I'd have given the 👍 Almost to the 🏁 

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-02-19 14:39 UTC, mcrd25 commented on app copy/views/posts/index.html.erb
> +    <%# <img src="img_avatar3.png" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;"> %>
Please remove commented out code. 
As can be seen from [this screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)
It is better to delete commented code. If you need to review a previous version of your code, use git history. 🙂

2020-02-19 14:39 UTC, mcrd25 commented on spec/controllers/events_controller_spec.rb
> +  # describe 'POST #create' do
Please remove commented out code. 
As can be seen from [this screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)
It is better to delete commented code. If you need to review a previous version of your code, use git history. 🙂

2020-02-19 14:39 UTC, mcrd25 commented on spec/controllers/users_controller_spec.rb
> +  # describe 'POST #create' do
Please remove commented out code. 
As can be seen from [this screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)
It is better to delete commented code. If you need to review a previous version of your code, use git history. 🙂

2020-02-19 18:39 UTC, wathigo approved these changes
### Changes Approved :heavy_check_mark: 
Hi Denis :wave: 
Great work implementing the suggested changes

**You may proceed to the next project.**

**Good luck :four_leaf_clover:** 
**Simon Wathigo**

2020-02-19 18:59 UTC, merged